routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaterkitController;
use App\Http\Controllers\LanguageController;

use App\Http\Controllers\UserController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\PengaduanController;
use App\Http\Controllers\PengadaanController;
use App\Http\Controllers\DivisiController;
use App\Http\Controllers\OutletController;
use App\Http\Controllers\ListresponController;
use App\Http\Controllers\ListResponPengadaanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Auth::routes();

Route::group(['middleware' => ['auth']], function () { 
    Route::get('/', [StaterkitController::class, 'home'])->name('home');
    Route::get('home', [StaterkitController::class, 'home'])->name('home');

    //COMPANY ROUTE
    Route::get('company/table', [CompanyController::class, 'tables'])->name('company.table');
    Route::resource('company', CompanyController::class);
    //---------------------------------------------
    //USER ROUTE
    Route::get('user/table', [UserController::class, 'tables'])->name('user.table');
    Route::resource('user', UserController::class);
    //---------------------------------------------
    //PENGADUAN ROUTE
    Route::get('pengaduan/table', [PengaduanController::class, 'tables'])->name('pengaduan.table');
    Route::get('pengaduan/done/{id}', [PengaduanController::class, 'done'])->name('pengaduan.done');
    Route::post('pengaduan/estimasi', [PengaduanController::class, 'estimasi'])->name('pengaduan.estimasi');
    Route::get('pengaduan/listrespon', [ListresponController::class, 'index'])->name('pengaduan.listrespon');
    Route::get('pengaduan/listrespon/table', [ListresponController::class, 'tables'])->name('pengaduan.listrespon.table');
    Route::post('pengaduan/input1', [ListresponController::class, 'input1'])->name('pengaduan.input1');
    Route::resource('pengaduan', PengaduanController::class);
    
    //---------------------------------------------
    //PENGADAAN ROUTE
    Route::get('pengadaan/table/{type}', [PengadaanController::class, 'tables'])->name('pengadaan.table');
    Route::get('pengadaan/listrespon', [ListResponPengadaanController::class, 'index'])->name('pengadaan.listrespon');
    Route::get('pengadaan/listrespon/table//{type}', [ListResponPengadaanController::class, 'tables'])->name('pengadaan.listrespon.table');
    
    Route::post('pengadaan/input1', [PengadaanController::class, 'input1'])->name('pengadaan.input1');
    Route::post('pengadaan/input2', [PengadaanController::class, 'input2'])->name('pengadaan.input2');
    Route::post('pengadaan/input3', [PengadaanController::class, 'input3'])->name('pengadaan.input3');
    Route::post('pengadaan/foto', [PengadaanController::class, 'foto'])->name('pengadaan.foto');
    Route::resource('pengadaan', PengadaanController::class);
    //---------------------------------------------
    //Divisi ROUTE
    Route::get('divisi/table', [DivisiController::class, 'tables'])->name('divisi.table');
    Route::resource('divisi', DivisiController::class);
    //---------------------------------------------
    //Outlet ROUTE
    Route::get('outlet/table', [OutletController::class, 'tables'])->name('outlet.table');
    Route::resource('outlet', OutletController::class);
    //---------------------------------------------


    // locale Route
    Route::get('lang/{locale}', [LanguageController::class, 'swap']);

});

resources/views/content/pages/form.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'User Edit')

@section('vendor-style')
  {{-- Vendor Css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/flatpickr/flatpickr.min.css')) }}">
@endsection

@section('page-style')
  {{-- Page Css files --}}
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/forms/pickers/form-flat-pickr.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/forms/form-validation.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/pages/app-user.css')) }}">

  <link rel="stylesheet" href="{{ asset('css/summernote/summernote.min.css') }}">
@endsection

@section('content')
<!-- users edit start -->
<section class="app-user-edit">
  <div class="card">
    <div class="card-body">

      <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
          <a
            class="nav-link d-flex align-items-center active"
            id="form1-tab"
            data-toggle="tab"
            href="#form1"
            aria-controls="form1"
            role="tab"
            aria-selected="true"
          >
            <i data-feather="user"></i><span class="d-none d-sm-block">{{$page_title}}</span>
          </a>
        </li>
      </ul>

        <!-- Form1 Tab starts -->
        <div class="tab-pane active" id="form1" aria-labelledby="form1-tab" role="tabpanel">

          @include("_includes.alert")

          @php $disabled = $page_type == 'view' ? 'disabled' : '' @endphp

          <!-- users edit account form start -->
          <form class="form-validate" id="Form_Input" method="{{ !empty($method) ? $method : 'POST' }}" action="{{ $form_action }}" enctype="multipart/form-data">
            @csrf
            @if(empty($method))
              {{ $page_type == 'create' ? '' : method_field('PUT') }}
            @endif

            <div class="media mb-2">
              <img
                src="../../../alhikmah/public/{{ $item->logo }}"
                alt="users avatar"
                class="user-avatar users-avatar-shadow rounded mr-2 my-25 cursor-pointer"
                style="max-width:600px"
              />
              <div class="media-body mt-50">
                <div class="col-12 d-flex mt-1 px-0">
                  <label class="btn btn-primary mr-75 mb-0" for="change-picture">
                    <span class="d-none d-sm-block">Change Picture</span>
                    <input
                      name="logo"
                      class="form-control"
                      type="file"
                      id="change-picture"
                      hidden
                      accept="image/png, image/jpeg, image/jpg"
                    />
                    <span class="d-block d-sm-none">
                      <i class="mr-0" data-feather="edit"></i>
                    </span>
                  </label>
                </div>
              </div>
            </div>

            <div class="row">
            
              <div class="col-md-4">
                <div class="form-group">
                  <label for="name">Nama</label>
                  <input
                    type="text"
                    class="form-control @error('name') is-invalid @enderror"
                    value="{{ !empty($item->name) ? $item->name : old('name') }}"
                    name="name"
                    id="name"
                    {{ $disabled }}
                  />
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="phone_1">Telepon 1</label>
                  <input
                    type="text"
                    class="form-control @error('phone_1') is-invalid @enderror"
                    value="{{ !empty($item->phone_1) ? $item->phone_1 : old('phone_1') }}"
                    name="phone_1"
                    id="phone_1"
                    {{ $disabled }}
                  />
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="email_1">Email 1</label>
                  <input
                    type="email"
                    class="form-control @error('email_1') is-invalid @enderror"
                    value="{{ !empty($item->email_1) ? $item->email_1 : old('email_1') }}"
                    name="email_1"
                    id="email_1"
                    {{ $disabled }}
                  />
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="phone_2">Telepon 2</label>
                  <input
                    type="text"
                    class="form-control @error('phone_2') is-invalid @enderror"
                    value="{{ !empty($item->phone_2) ? $item->phone_2 : old('phone_2') }}"
                    name="phone_2"
                    id="phone_2"
                    {{ $disabled }}
                  />
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="email_2">Email 2</label>
                  <input
                    type="email"
                    class="form-control @error('email_2') is-invalid @enderror"
                    value="{{ !empty($item->email_2) ? $item->email_2 : old('email_2') }}"
                    name="email_2"
                    id="email_2"
                    {{ $disabled }}
                  />
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                </div>
              </div>


              <div class="col-md-6">
                <div class="form-group">
                  <label for="description">Desktipsi Perusahaan</label>
                  <textarea
                    class="form-control summernote @error('description') is-invalid @enderror"
                    name="description"
                    id="description"
                    rows="4"
                    {{ $disabled }}
                  >{{ !empty($item->description) ? $item->description : old('description') }}</textarea>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label for="address">Alamat</label>
                  <textarea
                    class="form-control summernote @error('address') is-invalid @enderror"
                    name="address"
                    id="address"
                    rows="4"
                    {{ $disabled }}
                  >{{ !empty($item->address) ? $item->address : old('address') }}</textarea>
                </div>
              </div>

              <div class="col-12 d-flex flex-sm-row flex-column mt-2">
                @if ($page_type == "edit" || $page_type == "create")
                <button type="submit" class="btn btn-primary mb-1 mb-sm-0 mr-0 mr-sm-1">{{ $page_type == 'create' ? 'Create Company' : 'Save Changes' }}</button>
                <button type="reset" class="btn btn-outline-secondary mb-1 mb-sm-0 mr-0 mr-sm-1">Reset</button>
                @endif
                <a href="{{ route('company.index') }}" class="btn btn-danger btn-outline-secondary">Back</a>
              </div>
            </div>
          </form>
          <!-- users edit account form ends -->
        </div>
        <!-- Form1 Tab ends -->

      </div>

    </div>
  </div>
</section>
<!-- users edit ends -->
@endsection

@section('vendor-script')
  {{-- Vendor js files --}}
  <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/pickers/flatpickr/flatpickr.min.js')) }}"></script>
@endsection

@section('page-script')
  {{-- Page js files --}}
  <script src="{{ asset(mix('js/scripts/components/components-navs.js')) }}"></script>
  <script src="{{ asset('css/summernote/summernote.min.js') }}"></script>

  <script>
    $(document).ready(function() {
      $('.summernote').summernote();
    });
  </script>

  <script type="text/javascript">
    $(function () {
      'use strict';

      //Select2-------------------------
      $(".basic-select2").select2();
      //Select2-------------------------

      // Change user profile picture-------------------------
      var changePicture = $('#change-picture');
      var userAvatar = $('.user-avatar');

      if (changePicture.length) {
        $(changePicture).on('change', function (e) {
          var reader = new FileReader(),
            files = e.target.files;
          reader.onload = function () {
            if (userAvatar.length) {
              userAvatar.attr('src', reader.result);
            }
          };
          reader.readAsDataURL(files[0]);
        });
      }
      // Change user profile picture-------------------------

      // Validation-------------------------
      var form = $('.form-validate');
      if (form.length) {
        $(form).each(function () {
          var $this = $(this);
          $this.validate({
            submitHandler: function (form, event) {
              form.submit();
            },
            rules: {
              name: {
                required: true
              },
            }
          });
        });
      }
      // Validation-------------------------
      
    });
  </script>
@endsection

resources/views/content/pages/list.blade.php
@extends('layouts/contentLayoutMaster')

@section('title')
  {{$page_title}}
@endsection

@section('vendor-style')
  {{-- Page Css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap4.min.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap4.min.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap4.min.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/toastr.min.css')) }}">
@endsection

@section('page-style')
  {{-- Page Css files --}}
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/forms/form-validation.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/pages/app-user.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/extensions/ext-component-toastr.css')) }}">
@endsection

@section('content')
<!-- users list start -->
<section class="app-user-list">
  <!-- list section start -->
  <div class="card">

    @include("_includes.alert")

    <!--begin::Header-->
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
      <div class="card-title">
        <h3 class="card-label">{{$page_title}}</h3>
      </div>
      <div class="card-toolbar">
        <!--begin::Button-->
        <!--<a href="{{route('company.create')}}" class="btn btn-primary font-weight-bolder">
        <span class="fa fa-plus-circle"></span> Add Data</a>-->
        <!--end::Button-->
      </div>
    </div>
    <!--end::Header-->


    <!--begin::Body-->
    <div class="card-body">
      <div class="card-datatable table-responsive">
        <table class="table table-bordered yajra-datatable">
          <thead class="thead-light">
            <tr>
              <th></th>
              <th>Nama</th>
              <th>Alamat</th>
              <th>Phone 1</th>
              <th>Email 1</th>
              <th>Actions</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
    <!--end::Body-->
  </div>
  <!-- list section end -->
</section>
<!-- users list ends -->
@endsection

@section('vendor-script')
  {{-- Vendor js files --}}
  <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap4.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap4.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/extensions/toastr.min.js')) }}"></script>
@endsection

@section('page-script')
  {{-- Page js files --}}
  <script type="text/javascript">
    $(function () {
      var table = $('.yajra-datatable').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('company.table') }}",
          columns: [
              {data: 'DT_RowIndex', name: 'DT_RowIndex'},
              {data: 'name', name: 'name'},
              {data: 'description', name: 'description'},
              {data: 'phone_1', name: 'phone_1'},
              {data: 'email_1', name: 'email_1'},
              {
                  data: 'action', 
                  name: 'action', 
                  orderable: true, 
                  searchable: true
              },
          ]
      });
      
    });

  </script>
@endsection